### PR TITLE
Debugging experience improvements.

### PR DESCRIPTION
**Pull request by psiha**

### CODE REVIEW

**Comment by jfalcou** [comment]
You patched the autogenerated file. YOu should apply your changes to the correspondign files in src/ or it will get lost next time we regenrate the aggrgated file

**Comment by psiha** [comment]
> You patched the autogenerated file. YOu should apply your changes to the correspondign files in src/ or it will get lost next time we regenrate the aggrgated file

oh dear, this is going to be some work 🙈 :P

**Comment by jfalcou** [comment]
Sorry. I should make a small page about how to handle that.
Change in src then you can run the `kumi-standalone` target to generate the main .hpp
This requires Python 3.

**Comment by jfalcou** [comment]
I replicated it, no worries

**Pull request closed without merging**
